apiVersion: v1
kind: Service
metadata:
  name: grcp-svc
spec:
  ports:
  - name: grcp-port
    port: 3000
    targetPort: 3800
  selector:
      name: grcp-deploy
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grcp-deploy
  namespace: so1p2
spec:
  selector:
    matchLabels:
      name: grcp-deploy
  replicas: 1
  template:
    metadata:
      labels:
        name: grcp-deploy
    spec:
      containers:
      - name: grcp-client
        image: hugoses202002793/grcp-client
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "250m"
        ports:
        - containerPort: 3800
      - name: grcp-server
        image: hugoses202002793/grcp-server
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "250m"
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST_REDIS
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: DB_HOST_REDIS
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: DB_DATABASE
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: DB_PASSWORD
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: DB_USER
      imagePullSecrets:
        - name: dockerhubpull
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-grcp
  namespace: so1p2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grcp-deploy
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50